### ISSUE TITLE
eml327

### ISSUE THREAD

**Issue by DevX-Cipher** [LegacyNsfw/PcmHacks#189]
hi this isnt a issue but was wondering if you guys ever got it to work with elm327 cables and if not im willing to help also where can i buy these other cables ect

**Comment by DevX-Cipher** [comment]
added STN1170 for elm327

**Comment by Gampyg28** [comment]
Are you saying you have a device (cable) with a STN1170 chip and it works ??
If yes and you are interested in further testing and adding it to the supported device list that would be awesome!
If yes, It would be simpler if you were to join pcmhacking.net and posting there ...

Thank you!

**Comment by DevX-Cipher** [comment]
yes but atm im trying to get it to work with FTDI

**Comment by antuspcm** [comment]
regarding the first comment, the original elm cables can not handle packets long enough to do the flash. They cant retrieve the vin packets causing errors at the get properties stage, and they also cant support the flash commands of the format prio,dest,src,mode,mode2,len,len,addr,addr,addr,data,cs (12 bytes, inc. checksum) which would be the minimum size to write 1 byte at a time. You'd need to create a completely non-standard protocol just for that device to use no larger than 9 byte packets (with long mode enabled) and for all that effort it'd be the slowest way to flash by a absolutely huge margin due to the overheads and limit of 1x speed, which also increases the chances of failure.

**Comment by DevX-Cipher** [comment]
yes i know but why not just add it anyway oh btw i reversed engineered this guys software called ls1 flash tool and the cables he uses are allpro and charges $400 for

**Comment by DevX-Cipher** [comment]
does anyone if there is a holden version for this cable kkl vag-com 409.1

**Comment by antuspcm** [comment]
Because of the reasons above. It would need to be another app as it'd need to be significantly different. I wont be creating that app because personally I think it would be a waste of my time, with bad outcomes. A lot of unhappy people would complain about the ridiculously slow speed and vent at the developer and we would get asked where to find a working elm interface way to often (which we could not answer). If you want to fork the project and rip in to it and create this new elm protocol, it is open source and you can. But there is no intention for pcm hammer to go down this road.

As for kkl, forget it, its a different protocol, an not relevant at all. You should learn a little about your car, what computer is in it, and OBD2 protocols. If you just want to use pcmhammer look at the list of supported interfaces on the wiki page and buy one of those.

**Comment by DevX-Cipher** [comment]
yes i know but why not add it to be honest just helps other developers in the future

**Comment by Tazzi3** [comment]
> yes i know but why not add it to be honest just helps other developers in the future

Your welcome to fork the project and try add ELM compliancy. For for the sake of reliability and speed, its not ideal in anyway.

**Comment by DevX-Cipher** [comment]
Have you done it yourself

**Comment by antuspcm** [comment]
Gampy just pointed the bit about the STN1170 to me. I read this as though you were saying ELM327, which is a very different device. If it is an STN device, which has much greater capability, then that changes my response. I'll re-open this ticket.

**Comment by DevX-Cipher** [comment]
im using elm327 wich that chip in i can read using forscan ect im adding it this project maybe im not sure just yet though

**Comment by antuspcm** [comment]
OK, well its not an elm327 then. This is the details of an elm327 from the elm company who originally invented the protocol and made the ELM327 just to codes. https://www.elmelectronics.com/products/ics/obd/ It does not respond to the command that where you get back STN1170. STN refers to https://ScanTool.Net/ and their chips, while being backward compatible, introduce new functionality over what the ELM327 can do, which enabled flashing with pcmhammer. They sell the chips to 3rd partys and put them in their own OBDLink devices. I think we might be able to add a fall back mode so unrecognized chips that do respond with STNxxxx run at a minimum speed so they at least work. And we can probably work with you to figure out how large we can make the packets on that device and add official support.

**Comment by DevX-Cipher** [comment]
yer im willing to help just trying to add elm327 device FT232 sorry ive been confusing myself with 3 different elm327 cables  sorry

**Comment by Tazzi3** [comment]
> Have you done it yourself

Yes I have. Iv developed with ELMs for 7+years to provide commercial products... I am fully aware of their limitations.
I am refering to official ELMs produced by elmelectronics. Other tools which are backwards compatible with ELM commands such as obdlinks have larger buffers which can help, but are still slow and restricted.

**Comment by DevX-Cipher** [comment]
yes of course so have you added ft323

**Comment by Gampyg28** [comment]
modz2014,
You are communicating with folks that have been doing this for many years (excluding myself, I'm the new kid on the block)
If it's been done, they have probably done it!

A FT232 device is just a USB UART device (USB to Serial), adding it is just like adding any other USB device to your computer, it adds a Serial Port (COMMx) to the Operating System, that Serial port is then used to access things like a elm327 device or a STN chipped device ...

If it is a CLONE FTDI device and you have tried to install it using Authentic FTDI drivers it may very well be garbage now because Authentic FTDI drivers disable clone devices they find, or at least used to, I do not know if they still do.

You say you have a device that has a STN1170 chip on it, that chip is typically accessed through a Serial Port in the Operating System, typically using a USB->Serial device like the FT232.

We may very well be able to get that STN1170 chipped device to work with PcmHammer.

After you get access to it on your computer, typically through a Serial Port.

**Comment by DevX-Cipher** [comment]
i have the officail elm327 with chip ft232 i cant get this to work with pchammer but the other chip i could

**Comment by DevX-Cipher** [comment]
also i found if the create for the android app will make it for IOS im been looking into doing this as well

**Comment by antuspcm** [comment]
So, I think I am starting to understand what you are trying to do. Lets do some fact checking.

1) You are building your own interface, implementing a chip with the elm327 pin configuration, and using a FTDI chip as a USB interface.

 Building your own interface is out of scope of this project. Most people are using off the shelf interfaces, Typically scantool.net OBDLink interfaces which contain the chip and the usb or bluetooth interface or a J2534 interface. Building your own interface is possible if you want to do that for fun or to learn, but if you just want to use pcmhammer then you are better of to buy a complete ready to use obdlink or j2534 interface which supports VPW protocol, most but not all do.

2) In your interface it sounds like you have the usb to serial working, and maybe you are swapping between an original elm327 chip and a pin for pin compatible STN chip in a socket and you are testing both? And the EL327 doesnt work with pcmhammer but the STN does?

Then your results are expected. This is as described above.

**Comment by DevX-Cipher** [comment]
I doing both I want to get elm327 working

**Comment by DevX-Cipher** [comment]
my elm327has chip ft232 which is can does VPW protocol

**Comment by antuspcm** [comment]
> regarding the first comment, the original elm cables can not handle packets long enough to do the flash. They cant retrieve the vin packets causing errors at the get properties stage, and they also cant support the flash commands of the format prio,dest,src,mode,mode2,len,len,addr,addr,addr,data,cs (12 bytes, inc. checksum) which would be the minimum size to write 1 byte at a time. You'd need to create a completely non-standard protocol just for that device to use no larger than 9 byte packets (with long mode enabled) and for all that effort it'd be the slowest way to flash by a absolutely huge margin due to the overheads and limit of 1x speed, which also increases the chances of failure.

I want to help you but I dont think you are reading my responses. Re-read the above, quoted from just over a week ago. the elm327 was not designed to flash cars. It talks the electrical VPW protocol, but it is too small and can not send or receive packets long enough for re-flash. The smallest interfaces use packet sizes of 128 bytes. The largest use packet sizes of 4k. The elm327 does 7 bytes, or 'more', typically 8 or maybe 9 when you enable long mode with command ATAL.

If you disagree you must fork pcmhammer and make significant changes through all the code to handle this very significant limitation. The result, *if* and its a very big if you can even succeed, it will be so slow it'll be joke. Seriously.

Lets say you receive 1 byte of payload data per packet after overheads. And lets say you get 5 packets per second (thats probably optimistic, the elm327 is a very slow pic processor with slow turnaround on a half duplex bus). Thats 5 bytes a second. so for the smaller P01 pcm it'll take 145 hours for a read - 6 days of your car turned on reading. And for the p59 it'll be 290 hours - yes 12 days nearly 2 weeks with ignition on, battery running doing a read. And we wont be able to put that code back in to pcmhammer because it'll break everything else because you wont be able to use the standard protocols, and pcms like the P04 can not do multi-part kernel transfers so they are flat out impossible. 

My numbers are kinda rough, but they are realistic.

**Comment by DevX-Cipher** [comment]
ok why dont you add to seperate section for people to play around with if you dont want it up there thats fine but up to you guys really

**Comment by Tazzi3** [comment]
> ok why dont you add to seperate section for people to play around with if you dont want it up there thats fine but up to you guys really

Anyone can edit PCMHammer as it is open source. If you understand the coding currently, you can easily add another device to the supported devices and begin adding its support. As Antus has indicated, an ELM cable would be ungodly slow.

**Comment by DevX-Cipher** [comment]
ok then i wont add this im looking at getting els27 offical cable but i have to wait until next year for it to be delivered

**Comment by antuspcm** [comment]
watch out for clones... https://forscan.org/forum/viewtopic.php?t=1904
thats a ford forum, vpw may or may not work (they may not have tested it). if your interface does not, you are on your own.
a genuine scantool.net obdlink would be a better low cost option. or GM MDI if you can afford it, as its J2534 and works with factory tools also.

**Comment by DevX-Cipher** [comment]
ok from ive asked about gm mdi apprently doesnt work on holden australian cars unless someone has tried it and it works

does it need to be genuine or can it be china copy stuff

**Comment by antuspcm** [comment]
Im not sure where you heard that. it does not work. Can you please create a new thread on pcmhacking if you have general questions, so that everyone can see it, and the answers and others will also be able to help. This area is for app development. As far as I know clones should work (there is nothing in pcmhammer specifically locking them out)

**Comment by DevX-Cipher** [comment]
ok will do

**Comment by DevX-Cipher** [comment]
is there a reason why obdlink mx not plus doesn't work with pcmhammer

**Comment by antuspcm** [comment]
Probably nobody tested it when we built v014. Try building the code in develop and let us know if that works for you. There are a number of changes to support more scantool devices and bigger buffers.

**Comment by DevX-Cipher** [comment]
yer i see it has obdlink mx chipset there in the code but i dont have the device yet
