### ISSUE TITLE
need help it wont read the seed or vin

### ISSUE THREAD

**Issue by OGJester420** [LegacyNsfw/PcmHacks#236]
[PcmHammer_debugLog_20211105@080240.txt](https://github.com/LegacyNsfw/PcmHacks/files/7488803/PcmHammer_debugLog_20211105%40080240.txt)

**Comment by antuspcm** [comment]
It looks like no data is coming back from the car at all. Is the key in the 'on' position? Does the interface work properly with any other software? If the car is on, and the interface is working, my guess is a wiring problem. Otherwise its possibly an incompatible car. Either way, I dont think this a software problem with pcmhammer. If you have any more information that points to it being a problem with Pcmhammer, please add it here and I'll re-open the issue.
